version: '3'

services:
  app:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    image: app:django
    container_name: second-django
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=060489a+
    container_name: postgres_db

