# Generated by Django 4.1.7 on 2023-02-24 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('university', models.CharField(default='Pamukkale University', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to='posts')),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.user')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
